// Code generated by goctl. DO NOT EDIT.
// Source: seckill.proto

package server

import (
	"context"

	"mall/service/seckill/rpc/internal/logic"
	"mall/service/seckill/rpc/internal/svc"
	"mall/service/seckill/rpc/types/seckill"
)

type SeckillServer struct {
	svcCtx *svc.ServiceContext
	seckill.UnimplementedSeckillServer
}

func NewSeckillServer(svcCtx *svc.ServiceContext) *SeckillServer {
	return &SeckillServer{
		svcCtx: svcCtx,
	}
}

func (s *SeckillServer) SeckillProducts(ctx context.Context, in *seckill.SeckillProductsRequest) (*seckill.SeckillProductsResponse, error) {
	l := logic.NewSeckillProductsLogic(ctx, s.svcCtx)
	return l.SeckillProducts(in)
}

func (s *SeckillServer) SeckillOrder(ctx context.Context, in *seckill.SeckillOrderRequest) (*seckill.SeckillOrderResponse, error) {
	l := logic.NewSeckillOrderLogic(ctx, s.svcCtx)
	return l.SeckillOrder(in)
}
